"""第二次迁移

Revision ID: 0c0a065086ab
Revises: 79c9cf29b574
Create Date: 2019-07-10 11:18:52.868706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0a065086ab'
down_revision = '79c9cf29b574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sc_brande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brandename', sa.String(length=20), nullable=True),
    sa.Column('carstyle', sa.String(length=20), nullable=True),
    sa.Column('carstyle_detail', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc_car',
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brande', sa.Integer(), nullable=True),
    sa.Column('sc_users_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('car_age', sa.Integer(), nullable=True),
    sa.Column('car_model', sa.String(length=10), nullable=True),
    sa.Column('car_gearbox', sa.Integer(), nullable=True),
    sa.Column('car_distance', sa.Integer(), nullable=True),
    sa.Column('car_num', sa.String(length=100), nullable=True),
    sa.Column('car_color', sa.String(length=10), nullable=True),
    sa.Column('car_oil_style', sa.String(length=10), nullable=True),
    sa.Column('car_emission_standard', sa.String(length=10), nullable=True),
    sa.Column('car_seat_num', sa.Integer(), nullable=True),
    sa.Column('car_transfer_num', sa.Integer(), nullable=True),
    sa.Column('car_inspect_annually', sa.String(length=10), nullable=True),
    sa.Column('car_compulsory_insurance', sa.String(length=10), nullable=True),
    sa.Column('car_commercial_insurance', sa.String(length=10), nullable=True),
    sa.Column('index_image_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['brande'], ['sc_brande.id'], ),
    sa.ForeignKeyConstraint(['sc_users_id'], ['sc_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['sc_car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sc_image')
    op.drop_table('sc_car')
    op.drop_table('sc_brande')
    # ### end Alembic commands ###
